WITH MEMBER_EMAIL AS
(
 SELECT
     PERSON_SERIAL,
     PERSON_EMAIL
 FROM
     (
         SELECT
             PERSON.SERIAL AS PERSON_SERIAL,
             PERSON_CONTACT.VALUE AS PERSON_EMAIL,
             ROW_NUMBER() OVER(PARTITION BY PERSON.SERIAL
                 ORDER BY PERSON_CONTACT.ORDINAL) AS MIN_ORDINAL

         FROM
             CORE.PERSON AS PERSON
                 INNER JOIN CORE.PERSON_CONTACT AS PERSON_CONTACT
                            ON PERSON.SERIAL = PERSON_CONTACT.PARENT_SERIAL
         WHERE
             (PERSON_CONTACT.CATEGORY = 'PE' OR PERSON_CONTACT.CATEGORY = 'BE')
           AND PERSON_CONTACT.VALUE IS NOT NULL
           AND PERSON_CONTACT.BAD_CONTACT = 'N'
           AND PERSON_CONTACT.EXPIRATION_DATE IS NULL

     )
 WHERE
         MIN_ORDINAL = 1
)

SELECT
    CARD_NUMBER,
    MEMBER_EMAIL.PERSON_EMAIL,
    PERSON.LAST_NAME || COALESCE((', ') || PERSON.FIRST_NAME, '') AS MEMBER_NAME,
    ACCOUNT_NUMBER
FROM
    CORE.CARD AS CARD

    INNER JOIN
        CORE.CARD_PLASTIC AS CARD_PLASTIC
        ON CARD.SERIAL = CARD_PLASTIC.PARENT_SERIAL
    INNER JOIN
        CORE.PERSON AS PERSON
        ON CARD_PLASTIC.PERSON_SERIAL = PERSON.SERIAL
    INNER JOIN
        CORE.ACCOUNT AS ACCOUNT
        ON CARD.PRIMARY_ACCOUNT_SERIAL = ACCOUNT.SERIAL
    LEFT OUTER JOIN
        MEMBER_EMAIL ON MEMBER_EMAIL.PERSON_SERIAL = PERSON.SERIAL
ORDER BY
    CARD_NUMBER